### ISSUE TITLE
Week numbers

### ISSUE THREAD

**Issue by pulkomandy** [HaikuArchives/Calendar#101]
In a profesionnal setting it is not uncommon to use week numbers. See https://en.wikipedia.org/wiki/ISO_week_date for how it is defined, but hopefully we can get it from ICU and not implement the math ourselves.

These should be visible next to the calendar (one per line). See for example the Linux utility Dayplanner:

https://mundo-tips.com/wp-content/uploads/2020/05/dayplanner-2.png

**Comment by humdingerb** [comment]
Our calender view already allows for this. Calender preferences offer a checkbox "Show week numbers in Calendar". Could be shortened to "Show week numbers"...

**Comment by humdingerb** [comment]
No change required then.
