### ISSUE TITLE
Add menu item "View | Show hidden events"

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Calendar#104]
That the users have to navigate to the events folder to un-hide a hidden event is a bit awkward.

Would it be possible to add a new checkmarkable menu item to "Show hidden events" in the View menu? Then you'd be able to un-hide an event via context menu, like all the other event actions.
Hidden events will have to show up ghosted or tinted or something.

**Comment by JadedCtrl** [comment]
It might be useful for deleted events to be also shown, too, so you can undelete without digging through the trash.

**Comment by humdingerb** [comment]
Yes. I guess there's no need for 2 items, just "Show hidden/deleted events".

**Comment by JadedCtrl** [comment]
Added with 9d8b43a

**Comment by humdingerb** [comment]
Why is this still open... :)
