### ISSUE TITLE
"Heatmap"-style day highlighting

### ISSUE THREAD

**Issue by JadedCtrl** [HaikuArchives/Calendar#106]
Right now, a day is highlighted in the calendar if it's the current day or if it has at least one event. It might help give a better impression of "busy" days by highlighting them heatmap-style, somehow.

The hard part is picking a color that doesn't distract too much, or collide with pre-existing tints.

**Comment by pulkomandy** [comment]
Maybe it could use colors from the events in that day? Or maybe that would be too busy and hard to read.

**Comment by humdingerb** [comment]
yeah. I think it may be best to get the system-provided selection colour and just tint it the more events a day has ; darker or brighter depending on if we're on a dark theme or standard theme. If that is possible...
