### ISSUE TITLE
Change tint colour of deleted events

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Calendar#113]
With Haiku's default theme, the background colour of deleted events is quite similar to the background of a selected item. Therefore a selected item appears almost like a deleted item:

![screenshot2](https://user-images.githubusercontent.com/6107158/146671061-1f4e90b6-3104-4ee0-97cf-17b6a538123f.png)

It's not the exact grey, but one can get confused.
Maybe a bit of red could be mixed in the colour of hidden/deleted events?

**Comment by humdingerb** [comment]
![screenshot3](https://user-images.githubusercontent.com/6107158/146677480-f2758c9e-b632-42a9-a8b8-a0ff5d7cb959.png)

This is with a
```
	if (severity >= 1)
		bgColor.red =- 5;
```
in [EventListItem.cpp#L65](https://github.com/HaikuArchives/Calendar/blob/master/src/EventListItem.cpp#L65)

I have to admit, I don't quite understand why it's not `bgColor.red =+ 5` to increase the red part of the colour and why lower values tint deeper than higher values... :)

What do you say, @JadedCtrl ?

**Comment by pulkomandy** [comment]
If you want to increase, use += (or -= to decrease). What you have here just sets the color to +5 (which is quite dark) or -5 (which will overflow and become 250, quite light), ignoring the previous value.

**Comment by humdingerb** [comment]
See, I am a crappy programmer... :)
I guess one has to find a more sophisticated solution to account for overflowing values. Help wanted...
It's nice that the Appearance prefs change colours live. Just twiddle the sliders for "List background" and see the changes.
