### ISSUE TITLE
Add Search/Filter Feature

### ISSUE THREAD

**Issue by harshit-sharma-gits** [HaikuArchives/Calendar#119]
If the user wants to look up a specific detail from the past or upcoming events, they can simply search the entire calendar by typing in a keyword, without having to manually scroll the calendar and search for that event.

**Comment by harshit-sharma-gits** [comment]
On discussing with the community, on [this](https://discuss.haiku-os.org/t/gsoc-22-project-improving-the-calendar-application/12139) thread, this was the best mockup suggested by @humdingerb 


![](https://discuss.haiku-os.org/uploads/default/optimized/2X/e/e6a99ea643f683be7ff3aa5d70751a362d86316b_2_579x500.png)

> * The Profile pop-up lets you choose what profile to display, once multiple profiles is implemented. The pop-up menu will have a checkmarkable list of the existnig profiles.
> * Same with the Categories
> * The emphasized textSearch text control filters for the search term.
> * The Clear button is a shortcut to remove all filters.
> The above criteria always relate to what tab is currently active and are applied live. That is, if you’re on the Month tab, you’ll get only the events of this month filtered accordingly. Same for Week and Day.
> We’d also need an Agenda view that’ll have all past, present and future events. This is a desirable view mode in any case, not just for the Filter & Search feature

**Comment by humdingerb** [comment]
Basically, yes. Though with [this post](https://discuss.haiku-os.org/t/gsoc-22-project-improving-the-calendar-application/12139/20) in that thread, I dialed down the widget additions to make it all much simpler.

It comes down to adding just the "Search" text control (which should be labelled "Filter").It'll work like Tracker's type-ahead filtering, applying the space-delimited terms to the query already used for the Day/Week/Month list, on the fields category, name, place, location.

"Profiles" would work the same. As you probably don't switch that often between profiles, it'll do to add them checkmarkable to the "View" menu in the menu bar (or a new menu "Profiles" there?).

Sounds good? Less work for you, simpler GUI for the users. :)

**Comment by humdingerb** [comment]
I took the liberty to add a new github label "GSoC'22" we can use for your work and edited the title of thiis ticket accordingly.

**Comment by harshit-sharma-gits** [comment]
I think this issue should be closed for now, as per PR #121

**Comment by humdingerb** [comment]
Right!
