### ISSUE TITLE
Calendar widget should be size-fixed

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Calendar#13]
Resizing the window shouldn't move/resize the calendar widget. Should be anchored to the top.

**Comment by ModeenF** [comment]
Think it is?

**Comment by ModeenF** [comment]
ah its anchored, but can be resizeed.

**Comment by humdingerb** [comment]
I created #73 for that.

**Comment by ModeenF** [comment]
Nice, then I can stop looking in to this.. :)
