### ISSUE TITLE
Indicate days with events in calendar widget

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Calendar#14]
The days with events should be bolded in the calendar widget.

**Comment by JadedCtrl** [comment]
I was looking into this earlier— as far as I can tell, there's no way to do this with [current BCalendarView](https://git.haiku-os.org/haiku/tree/src/kits/shared/CalendarView.cpp), there'd have to be some API modifications

 I'm thinking maybe add a private slot to the class that's an array of days that ought to be highlighted, and _DrawDays() could highlight all days matching ints in that array, along with the highlighted row/column, maybe iwth a different colour. The array'd be wiped at every SetDate(), maybe.

**Comment by pulkomandy** [comment]
Hi!

DrawDay in CalendarView is a virtual method, so we can create a
subclass, override that method, and make it draw anything extra we need.
This way there is no need to change the system CalendarView and we can
have all the level of customization we want.

**Comment by JadedCtrl** [comment]
Ahh, that's perfect then, thanks!

**Comment by humdingerb** [comment]
Was fixed with c6df4aaaa64e79db47ca0ec0a304ff3a092a33d6 , thanks!
