### ISSUE TITLE
Update the calendar view day names header on locale preferences change.

### ISSUE THREAD

**Issue by AkshayAgarwal007** [HaikuArchives/Calendar#2]

**Comment by AkshayAgarwal007** [comment]
Implementing BDateFormat::GetShortWeekDays() and using the same for fetching weekdaynames instead of BDate::ShortDayName() (which in turn uses strfime to get the day of week names, and LC_TIME to decide which locale to use) and updating BCalendarView on receiving B_LOCALE_CHANGED message would solve this. 
Some work in this regard: https://dev.haiku-os.org/ticket/13606

**Comment by humdingerb** [comment]
Can this be done for the whole GUI, not just calendar related strings (day names etc.)?
No other app of Haiku is able to change locale on the fly. While it would be cool, I imagine it would not be actually used "in the wild" very often...

**Comment by pulkomandy** [comment]
> No other app of Haiku is able to change locale on the fly.

The FirstBootPrompt can, but it's the only one. For most apps it is not worth the effort and extra code, as people rarely switch locales after the initial setup.

**Comment by humdingerb** [comment]
Forgot about the FirstBootPrompt... But we're on the same page, not worth the additional complexity. Closing.
