### ISSUE TITLE
Implement an agenda view

### ISSUE THREAD

**Issue by AkshayAgarwal007** [HaikuArchives/Calendar#25]
This shows the next events being lined up.

Something in this line...

**Now**
Event 0: Time elapsed or time remaining.

**Next**
Event 1:  in 20 minutes
Event 2: in 5 hours
Event 3: in 2 days
Event 5: next Sunday

Note: For relative date/time formatting a relative date/time formatter(part of locale kit) would have to be implemented. The same would also be useful in event notifications.

**Comment by CodeforEvolution** [comment]
I believe with @bach5000's work, this can be closed?

**Comment by scottmc** [comment]
Fixed with #47 dcaa470
