### ISSUE TITLE
Work on Haiku Locale kit.

### ISSUE THREAD

**Issue by AkshayAgarwal007** [HaikuArchives/Calendar#29]
1. Implement BDateFormat::GetWeekDays() : To get locale based weekday names in various format style (short/long/medium/abbreviated). For e.g Mon, Monday, Mo, M.
https://dev.haiku-os.org/ticket/13606
https://www.freelists.org/post/haiku-gsoc/Query-regarding-BDateFormat
2. The above function can be used to fix a bug with BCalendarView where the weekday names in the header doesn't get updated with locale preferences change.
3.  Extend BDateFormat::GetMonthName() to get month names in various format styles.
4.  Improve the current implementation of BDateFormat/BTimeFormat/BDateTimeFormat (avoid creating the date formatter on the ICU side multiple times keeping thread safety in mind).
5. Implement a relative DateTime formatter. 
http://icu-project.org/apiref/icu4c-latest/classicu_1_1RelativeDateTimeFormatter.html

**Comment by ModeenF** [comment]
Are this still valid? If so need it to be split in som way?

**Comment by humdingerb** [comment]
The calendar view seems to work fine with localisation. If there are bugs, please open new spcific issues.
