### ISSUE TITLE
Add timed computer task 

### ISSUE THREAD

**Issue by AkshayAgarwal007** [HaikuArchives/Calendar#35]
Add timed computer tasks (much like cron's operations). For example, instead of just texting you a reminder to start the weekly backup of your file server, it could kick off an ssh session that starts (and logs) the backup

Currently it only gives a notification before an event starts using BNotification.

**Comment by ModeenF** [comment]
What's the scope of thit program? This perhaps are nice to have but not primary task (if no one takes it and do it ;) )

**Comment by humdingerb** [comment]
I agree, way out of scope for this app.
