### ISSUE TITLE
Calendar doesn't show other Google calendars

### ISSUE THREAD

**Issue by j-koreth** [HaikuArchives/Calendar#45]
If you have other calendars under "My Calendars" the Calendar application doesn't show them.

**Comment by malbx** [comment]
I will work on this issue.

**Comment by j-koreth** [comment]
This issue is pretty old I'm not 100% sure if it's still there. I can try checking it out again

**Comment by humdingerb** [comment]
Google Calendar syncing has been removed because it stopped working (a Google API change?).
It has to first be implemented in a working way again to find bugs with it. :)
