### ISSUE TITLE
Integrating flutter into the calendar

### ISSUE THREAD

**Issue by Oluwaseun1235** [HaikuArchives/Calendar#50]
why don't we use flutter to design the calendar application, a thing about flutter is that it is cross-platform with out need to edit codes across several device platforms and flutter engine for desktop apps was launch just want to suggest if this could be used for the calendar it make the code portable and a good thing about flutter is that it uses a c++ rendering engine. 
If it is approved i would like to try this project out with flutter, though i don't have haiku, but i guess it should be able to work.

**Comment by pulkomandy** [comment]
No. HaikuArchives is about writing native applications for Haiku using the Haiku APIs. We are not interested in other toolkits.
