### ISSUE TITLE
Crashes when opening Preferences window

### ISSUE THREAD

**Issue by JadedCtrl** [HaikuArchives/Calendar#51]
When built from source, Calendar crashes whenever the Preferences window is opened— old builds, like the 2018 release HPKG work fine, though.

I'll try and replicate on another PC. Here's my [report file](https://coinsh.red/u/Calendar-7619-debug-11-04-2020-03-48-39.report.txt).

**Comment by humdingerb** [comment]
Can't reproduce here (Haiku hrev54042, 32bit).
Maybe it's some hickup when having an older settings file? I think I started from scratch, i.e. my files were just created.

**Comment by bitigchi** [comment]
Reproducible with the latest master and a fresh install.

**Comment by bitigchi** [comment]
Reproducible with the latest master and a fresh install.

**Comment by bitigchi** [comment]
Reproducible with the latest master and a fresh install.

**Comment by bitigchi** [comment]
Reproducible with the latest master and a fresh install.

**Comment by bitigchi** [comment]
Reproducible with the latest master and a fresh install.

**Comment by JadedCtrl** [comment]
I'm still getting it, too (on 64bit).

It looks like the problem is in the PreferenceWindow.cpp constructor, in the way fCurrentPreferences, fStartPreferences, and fTempPreferences are assigned. If you assign them in any other way, there's no crashing.

`PreferenceWindow::PreferenceWindow(Preferences* preferences)`  
...  
`*fCurrentPreferences = *preferences;`

I can't reproduce on 32bit either, I wonder why it only affects 64bit?

**Comment by malbx** [comment]
Hi @JadedCtrl.  It looks like we both have been working on the same issue.  I was able to identify what appears to be the root cause of the issue.  The assignment operator overloading for the preference class was not returning a value which lead to undefined behavior.  If you have some time, let me know what you think about my findings regarding the cause of the crash.

**Comment by JadedCtrl** [comment]
Hey @malbx. Your fix works perfectly, it looks like you got it. :)
