### ISSUE TITLE
Turkish translation added!

### ISSUE THREAD

**Issue by bitigchi** [HaikuArchives/Calendar#54]
Feel free to pull it from PolyGlot!

**Comment by ModeenF** [comment]
How do "we" pull stuff from there and where does it go?

**Comment by humdingerb** [comment]
Before a new release, we will export all catkeys from the project at Polyglot and put them in the "locales" folder. New languages will have to be added to the LOCALES in the Makefile. Also, when we change strings we have to upload the new en.catkeys to PolyGlot. I'll take care of it.

**Comment by ModeenF** [comment]
Nice, so nothing automatic about it :)

**Comment by humdingerb** [comment]
It's not magical yet, but a whole lot easier than manually managing new/updated strings in the catkeys of an app. :)

**Comment by bitigchi** [comment]
It looks like the translated strings are not reflected yet in the new version :/.

**Comment by humdingerb** [comment]
As with BeMines, this was the first release of a localized version. I forgot to change the recipe to add the catalogs. Done that now, new version is up at HaikUDepot in a minute.
