### ISSUE TITLE
Improve CategoryEdit UI

### ISSUE THREAD

**Issue by AkshayAgarwal007** [HaikuArchives/Calendar#6]
Possibly move ColorControl and ColorPreview into a separate panel and simply show a color well representing the category color in the CategoryEdit Window.

**Comment by ModeenF** [comment]
I think that this perhaps will be change.. If you get som syncing and perhaps showing more than one calendar? I don't know if outlook or Google has this feature. As I have a work and private account I'm more for different color of those.
