### ISSUE TITLE
Always respect Day/Week button toggle setting

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Calendar#65]
The state of the Day and Week button toggles should always determine what appears in the events list. Currently, if select a day in the date view while the Week button is active, the event list shows only the event of that selected day. It should show all the events of the selected day's week.

Can someone explain what the Agenda view is? I just seems to jump to 'today'...

**Comment by malbx** [comment]
Changes have been made to prevent the view from changing after a new date is selected.

There was a bug related to the Agenda view which has been fixed.  Selecting it should not have jumped to the current day.  It seems as though the main differentiator of the Agenda view is that is shows how much time remains until a given event of "Finished" if the event is in the past.

**Comment by humdingerb** [comment]
I'm not a big calendar app user in general, but the Agenda view doesn't strike me as particularly useful when it's very similar to the Day view...

**Comment by humdingerb** [comment]
Was fixed with #63. Thanks!
