### ISSUE TITLE
Remove Today button

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Calendar#66]
The "Today" button that jumps to the current date in the toolbar is confusing. It doesn't fit with the other buttons (Day, Week, Agenda) that toggle the event list content.

I propose to remove it and instead transform the view that shows todays date (above the calendar view) into a button. It's pretty intuitive that a click on today's date will take you to today.

**Comment by malbx** [comment]
There was a bug related to the "Today" button.  It was treated a view instead of a button that simply triggers a jump action.  The issue was address with PR #63.

It seems as though the main purpose of the button is to provide users with a quick way to return to the current day.  Given the fix, do you still believe that the button should be removed?

**Comment by humdingerb** [comment]
Thanks for the fix (and others :) )!

IMO, yes, the Today button should be removed, or at the very least moved.
I'd be nice if only the buttons that change the view of the event list (Day, Week, (added Month), Agenda) where above the event list. The "(go to)Today" button doesn't fit there.

The "Add event" (plus a "Remove event") button could be moved to the right in the column of the today's date view and the calender view.

A quick mockup: https://lutim.l4p1n.ch/3v0tpxW0/7m6Re8Og.png

**Comment by humdingerb** [comment]
For a revised mockup, please see issue #67.

**Comment by ModeenF** [comment]
Can't the button be a clickable text under the mothview?

**Comment by ModeenF** [comment]
Like this.. [https://l.l4p1n.ch/lqzshUAQ/siqN1GzB.png](url)

**Comment by ModeenF** [comment]
Can't the button be a clickable text under the mothview?
[https://l.l4p1n.ch/lqzshUAQ/siqN1GzB.png]https://l.l4p1n.ch/lqzshUAQ/siqN1GzB.png

**Comment by ModeenF** [comment]
Can't the button be a clickable text under the mothview?
https://l.l4p1n.ch/lqzshUAQ/siqN1GzB.png

**Comment by humdingerb** [comment]
I guess it could, but it doesn't really catch your eye. The button should at least say "Go to today".
I'm also for buttons that are not part of a toolbar being 'real' buttons, i.e. not just looking like it on mouse over. So a "Go to today" button that spans the whole width of the calendar view might look nice.

As I wrote in #67, I think the different views (Day, Week, Month etc) would work nicely as tab views instead of toggled buttons.
