### ISSUE TITLE
Layout improvments

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Calendar#67]
How about this layout to avoid too much grey space to the right of the event list:

![Image of Yaktocat](https://lutim.l4p1n.ch/fLpPePfK/CgfoiYEL.png)

The "today's date' is a mouse-over button that gets you to 'today'.
Not sure the Agenda view is needed, instead Month and Year might be added.

**Comment by humdingerb** [comment]
Come to think of it... Those picture buttons for Day/Week/Agenda views might be nice when in a toolbar. Here, however, having those as tab views could look nice and elegant.

**Comment by bitigchi** [comment]
Screens are mostly wider, not taller. Improving the right side would be better I reckon. The empty grey area under the month calendar ought to display event details, like long date, whether repeats or not, when it will be reminded, and additional notes.

**Comment by ModeenF** [comment]
I like bitigchi picture. Having a description under the month view,

**Comment by ModeenF** [comment]
In that way I like Outlook, Idag = ToDay, Mina Kalendrar = My calendars, Ny avtalat tid = new appointment
![image](https://user-images.githubusercontent.com/927121/103206174-86c54b00-48fb-11eb-8324-173eeb3fdaf8.png)

But on the other hand if I can choose/change the view. I don't really care how it looks (As long its black ;))

**Comment by bitigchi** [comment]
Yes, there should be an easy UI to select included calendars. macOS Calendar also has a sidebar on the left with checkboxes, which is hidden in above particular screenshot.

**Comment by ModeenF** [comment]
"The "today's date' is a mouse-over button that gets you to 'today'."
But if your in a different month and like to go todays date? I think that a today button/link are needed so that you don't need to got to the menu..

**Comment by JadedCtrl** [comment]
Multiple calendar support is common, but do these multiple calendars often also allow separate categories within them? If not, then categories might be a good substitute for multiple calendars (at least for sync and compatibility). Toggling which ones to show'd probably be nice, then.

**Comment by humdingerb** [comment]
>> "The "today's date' is a mouse-over button that gets you to 'today'."
> But if your in a different month and like to go todays date? I think that a today button/link are needed so that you don't need to got to the menu..

"Today's date" (the big one above the calender view) is, well, always today's date. It doesn't change when you change the date in the calender view and can therefore always bring to to today's date.

**Comment by ModeenF** [comment]
Ah so klick on to days date will show that date in the month view.. Guess I didn't know where you vas taling about :).

Sounds like a good Idée.

**Comment by humdingerb** [comment]
Yeah, it's practically what is the "Today" button now. With a tool tip "Go to today".

**Comment by humdingerb** [comment]
The layout has changed since this ticket was opened. It uses tabs now. I quite like it as it is now, no information overflow, just a list of events you double click for details. Let's open new specific tickets if needed and retire this one.
