### ISSUE TITLE
Remove Google sync

### ISSUE THREAD

**Issue by JadedCtrl** [HaikuArchives/Calendar#76]
Now Calendar's using queries instead of an SQL database, I think this opens the door to a fun use-case: syncing calendars with an FS add-on. A generic CalDAV/WebDAV filesystem could dump all calendar entries into the mount-point as event files, which can be edited and added to by the user… the same should be done for categories, etc.

I think on this train of thought, Calendar handling syncing at all is out-of-scope. Maybe it could forward the user to the WebDAV/CalDAV FS preferences program, but otherwise shouldn't have to worry about it at all.

The Google sync isn't doing anyone any good― it's been broken for a couple years now, and isn't as generic a solution as it could be. It might as well be removed, really.

**Comment by akshat01112001** [comment]
May I contribute on this project?

**Comment by pulkomandy** [comment]
Hi,
Help is always welcome!

**Comment by akshat01112001** [comment]
> Hi,
> Help is always welcome!

Thanks looking forward to your generous help

**Comment by scottmc** [comment]
See #86
